### ISSUE TITLE
Is a link to the presentation missing

### ISSUE THREAD

**Issue by imoonkey** [Khan/guacamole#11]
In the readme there is the following claim:
"For more information on what these mean, check out the presentation."

But I did not find any presentation reference in the document, or anywhere on the Internet related to the explanation of the estimated parameters.

It would be great to have those. Thanks :)

**Comment by elifeasley** [comment]
Thanks for this! It looks like the presentation is lost to time and space; I hope to make a new one soon. I'll have it link to Wikipedia instead!
