### ISSUE TITLE
python chokes on path of 'start_mirt_pipeline.py --train' in windows

### ISSUE THREAD

**Issue by bwanaaa** [Khan/guacamole#12]
I successfully generated sample data in windows 7 (using the python from an anaconda install) with:
`python start_mirt_pipeline.py --generate`

and got:
`If you find that not all cores are being used, try installing affinity.
Generating Responses
Generated responses for 500 students and 10 problems`

However training with this:
`python start_mirt_pipeline.py --train`

gives this"
`If you find that not all cores are being used, try installing affinity.
Training MIRT models
Traceback (most recent call last):
  File "start_mirt_pipeline.py", line 273, in <module>
    main()
  File "start_mirt_pipeline.py", line 183, in main
    run_with_arguments(arguments)
  File "start_mirt_pipeline.py", line 247, in run_with_arguments
    generate_model_with_parameters(arguments)
  File "start_mirt_pipeline.py", line 202, in generate_model_with_parameters
    model_training_util.mkdir_p(out_dir_name)
  File "C:\Users\Stefan\Downloads\guacamole-master\train_util\model_training_util.py", line 44, in mkdir_p
    os.makedirs(path)
  File "C:\Users\Stefan\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Stef
an\\Downloads\\guacamole-master/sample_data/models/1_no_time_2015-12-04 14:02:30.913000/'`

Obviously windows path structure is different than unix so the script is choking on
`'C:\\Users\\Stef
an\\Downloads\\guacamole-master/sample_data/models/1_no_time_2015-12-04 14:02:30.913000/'`

I tried:
`python start_mirt_pipeline.py --train --data_file "C:\Users\Stefan\Downloads\guacamole-master\sample_data\all.resposes"`

but get the same error.

How can this be fixed?

**Comment by bwanaaa** [comment]
sorry about the typo- I really typed
`python start_mirt_pipeline.py --train --data_file "C:\Users\Stefan\Downloads\guacamole-master\sample_data\all.responses`

**Comment by bwanaaa** [comment]
in 'start_mirt_pipeline.py' I changed

`os.path.abspath(__file__)) + '/sample_data/models/model.json',`
and
`path = arguments.model_directory + params + '/'`
and
`out_dir_name = arguments.model_directory + param_str + '/'`

to

`os.path.abspath(__file__)) + '\sample_data\models\\',`
and
`path = arguments.model_directory + params + '\\'`
and
`out_dir_name = arguments.model_directory + param_str + '\\'


but still get the same error.

The script works fine on OS X.

**Comment by dpipkin** [comment]
Pull request #13 should fix this. The problem was that windows doesn't like colons in their filenames.

**Comment by dpipkin** [comment]
@eliawry you can close this issue now :sweat_smile:

**Comment by eliawry** [comment]
Thanks :)
